# Generated by Django 5.0.7 on 2024-07-31 18:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'authors',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
